/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicRegisterImport } from './routes/_public/register'
import { Route as PublicLoginImport } from './routes/_public/login'
import { Route as ProtectedHomeImport } from './routes/_protected/home'
import { Route as ProtectedLayoutImport } from './routes/_protected/_layout'

// Create/Update Routes

const PublicRegisterRoute = PublicRegisterImport.update({
  id: '/_public/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const PublicLoginRoute = PublicLoginImport.update({
  id: '/_public/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedHomeRoute = ProtectedHomeImport.update({
  id: '/_protected/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedLayoutRoute = ProtectedLayoutImport.update({
  id: '/_protected/_layout',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected/_layout': {
      id: '/_protected/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeImport
      parentRoute: typeof rootRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginImport
      parentRoute: typeof rootRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '': typeof ProtectedLayoutRoute
  '/home': typeof ProtectedHomeRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
}

export interface FileRoutesByTo {
  '': typeof ProtectedLayoutRoute
  '/home': typeof ProtectedHomeRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_protected/_layout': typeof ProtectedLayoutRoute
  '/_protected/home': typeof ProtectedHomeRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/home' | '/login' | '/register'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/home' | '/login' | '/register'
  id:
    | '__root__'
    | '/_protected/_layout'
    | '/_protected/home'
    | '/_public/login'
    | '/_public/register'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ProtectedLayoutRoute: typeof ProtectedLayoutRoute
  ProtectedHomeRoute: typeof ProtectedHomeRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  ProtectedLayoutRoute: ProtectedLayoutRoute,
  ProtectedHomeRoute: ProtectedHomeRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_protected/_layout",
        "/_protected/home",
        "/_public/login",
        "/_public/register"
      ]
    },
    "/_protected/_layout": {
      "filePath": "_protected/_layout.tsx"
    },
    "/_protected/home": {
      "filePath": "_protected/home.tsx"
    },
    "/_public/login": {
      "filePath": "_public/login.tsx"
    },
    "/_public/register": {
      "filePath": "_public/register.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
