/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProtectedRegisterImport } from './routes/_protected/register'
import { Route as ProtectedLoginImport } from './routes/_protected/login'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRegisterRoute = ProtectedRegisterImport.update({
  id: '/_protected/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedLoginRoute = ProtectedLoginImport.update({
  id: '/_protected/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected/login': {
      id: '/_protected/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof ProtectedLoginImport
      parentRoute: typeof rootRoute
    }
    '/_protected/register': {
      id: '/_protected/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof ProtectedRegisterImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof ProtectedLoginRoute
  '/register': typeof ProtectedRegisterRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof ProtectedLoginRoute
  '/register': typeof ProtectedRegisterRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_protected/login': typeof ProtectedLoginRoute
  '/_protected/register': typeof ProtectedRegisterRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register'
  id: '__root__' | '/' | '/_protected/login' | '/_protected/register'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedLoginRoute: typeof ProtectedLoginRoute
  ProtectedRegisterRoute: typeof ProtectedRegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedLoginRoute: ProtectedLoginRoute,
  ProtectedRegisterRoute: ProtectedRegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_protected/login",
        "/_protected/register"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_protected/login": {
      "filePath": "_protected/login.tsx"
    },
    "/_protected/register": {
      "filePath": "_protected/register.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
